export enum ActionType {
    CLEAR_MESSAGES = 'CLEAR_MESSAGES',
    APPEND_MESSAGE = 'APPEND_MESSAGE',
    SELECT_PROPERTY = 'SELECT_PROPERTY',
    DESELECT_PROPERTY = 'DESELECT_PROPERTY',
    HIDE_PROPERTY = 'HIDE_PROPERTY',
    UNHIDE_PROPERTY = 'UNHIDE_PROPERTY',
}
